name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Make sure to double check if your issue is worth asking. Done? Ok go ahead and submit your issue!'
        pr-message: 'Make sure to double check if your pull request is 100% done. Done? Ok go ahead and submit your pull request!'
